site_name: ترفندهای GIS
repo_name: gishacks/main
repo_url: https://github.com/gishacks/main
edit_uri: ""
copyright: Copyright &copy; 2023 GIS Hacks
plugins:
  - blog:
      blog_dir: . 
  - search
  - encryptcontent:
      title_prefix: '🔒'
      summary: 'این صفحه شامل مجموعه یادداشت‌های جلسات دوره است و برای شرکت‌کنندگان دوره قابل دسترس است'
      placeholder: 'پسورد'
      placeholder_user: 'نام کاربری'
      password_button_text: 'ورود'
      password_button: True
      decryption_failure_message: 'نام کاربری یا پسورد اشتباه است..'
      encryption_info_message: 'نیاز به تأیید مجدد.'  
      remember_keys: true # keys from keystore will temporarily saved to sessionStorage
      remember_password: true # the entered credentials are not saved
      password_inventory:
        secret:
            pygis1: !ENV PASSWORD1_FROM_ENV
  - tags
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - custom-skip-class-name
      auto_caption: false
      caption_position: bottom
      background: white
      shadow: true
      manual: false

theme:
  custom_dir: docs/overrides
  features:
    - navigation.indexes 
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  language: fa
  font:
    text: Vazirmatn
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/gishacks
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/gishacks
extra_css: [extra.css]
nav:
  - Home: index.md
  - ترفندها: 
    - ترفندها: hacks/index.md
    - افزودن نقشه پایه: hacks/basemaps.md
    - نقشه حرارتی زمان‌مند: hacks/heatmaps.md
    - تحلیل حوزه آب‌خیز: hacks/watershed.md
    - نقشه پوشش زمین: hacks/landcover.md
    #- Adding a landing page: setup/adding-a-landing-page.md
  - دوره‌های آموزشی:
    - دوره‌های آموزشی: courses/index.md
    - کار با داده‌های جهانی: courses/global-data.md
    - ورود به دنیای برنامه‌نویسی پایتون در GIS: 
      - معرفی دوره: courses/pygis101.md
      - جلسه ۱-مبانی: courses/pygis101/session1.md
      - جلسه ۲-وکتور: courses/pygis101/session2.md
      - جلسه ۳-رستر: courses/pygis101/session3.md
      - جلسه ۴-آمار: courses/pygis101/session4.md
  - درباره: about.md
  - تماس: contact.md

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format  
