site_name: ترفندهای GIS
repo_name: gishacks/main
repo_url: https://github.com/gishacks/gishacks.github.io
edit_uri: edit/main/docs/
copyright: Copyright &copy; 2023 GIS Hacks
plugins:
  - blog:
      blog_dir: . 
  - search
  - encryptcontent:
      title_prefix: '🔒'
      summary: 'این صفحه شامل مجموعه یادداشت‌های جلسات دوره است و برای شرکت‌کنندگان دوره قابل دسترس است'
      placeholder: 'پسورد'
      placeholder_user: 'نام کاربری'
      password_button_text: 'ورود'
      password_button: True
      decryption_failure_message: 'نام کاربری یا پسورد اشتباه است..'
      encryption_info_message: 'نیاز به تأیید مجدد.'  
      remember_keys: true # keys from keystore will temporarily saved to sessionStorage
      remember_password: true # the entered credentials are not saved
      password_inventory:
        secret:
            pygis1: !ENV PASSWORD1_FROM_ENV
  - tags
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - custom-skip-class-name
      auto_caption: false
      caption_position: bottom
      background: white
      shadow: true
      manual: false

theme:
  custom_dir: docs/overrides
  features:
    - navigation.indexes 
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    # - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  language: fa
  font:
    text: Vazirmatn
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/gishacks
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/gishacks
extra_css: [extra.css]
nav:
  - Home: index.md
  - ترفندها: 
    - ترفندها: hacks/index.md
    - افزودن نقشه پایه: hacks/basemaps.md
    - نقشه حرارتی زمان‌مند: hacks/heatmaps.md
    - تحلیل حوزه آب‌خیز: hacks/watershed.md
    - نقشه پوشش زمین: hacks/landcover.md
    #- Adding a landing page: setup/adding-a-landing-page.md
  - دوره‌های آموزشی:
    - دوره‌های آموزشی: courses/index.md
    - کار با داده‌های جهانی: courses/global-data.md
    - آشنایی با GIS:
      - معرفی دوره: courses/gis101.md
      - جلسه ۱-مفاهیم GIS: courses/gis101/session1.md
      - جلسه ۲-آشنایی با داده‌ها و نرم‌افزار: courses/gis101/session2.md
      - جلسه ۳-نمایش داده‌ها ۱: courses/gis101/session3.md
      - جلسه ۴-نمایش داده‌ها ۲: courses/gis101/session4.md
      - جلسه ۵-قاب‌بندی ساده: courses/gis101/session5.md
      - جلسه ۶-قاب‌بندی حرفه‌ای: courses/gis101/session6.md
      - جلسه ۷-گزارش آماری جداول: courses/gis101/session7.md
      - جلسه ۸-گزارش آماری حرفه‌ای: courses/gis101/session8.md
      - جلسه ۹-انتخاب توصیفی: courses/gis101/session9.md
      - جلسه ۱۰-انتخاب ترسیمی: courses/gis101/session10.md
      - جلسه ۱۱-تحلیل موقعیت لایه‌ها: courses/gis101/session11.md
      - جلسه ۱۲-تحلیل نزدیکی: courses/gis101/session12.md
      - جلسه ۱۳-تحلیل مطلوبیت: courses/gis101/session13.md
      - جلسه ۱۴-تحلیل فضایی ۱: courses/gis101/session14.md
      - جلسه ۱۵-تحلیل فضایی ۲: courses/gis101/session15.md
      - جلسه ۱۶-تحلیل سطح: courses/gis101/session16.md
      - جلسه ۱۷-تحلیل شبکه: courses/gis101/session17.md
      - جلسه ۱۸-امتیازدهی و وزن‌دهی: courses/gis101/session18.md
      - جلسه ۱۹-ساخت لایه GIS: courses/gis101/session19.md
      - جلسه ۲۰-جمع‌آوری مستقیم داده: courses/gis101/session20.md
      - جلسه ۲۱-ساخت نقشه آنلاین: courses/gis101/session21.md
      - جلسه ۲۲-ساعت روایت داده‌ها: courses/gis101/session22.md
    - GIS پیشرفته:
      - معرفی دوره: courses/advgis.md
      - جلسه ۱ - معرفی و برنامه‌ریزی: courses/advgis/session1.md
      - جلسه ۲ - تحلیل سطح فضایی: courses/advgis/session2.md
      - جلسه ۳ - تحلیل مطلوبیت فضایی: courses/advgis/session3.md
      - جلسه ۴ - تحلیل هیدرولوژیک فضایی: courses/advgis/session4.md
      - جلسه ۵ - ایجاد داده شبکه‌ای: courses/advgis/session5.md
      - جلسه ۶ - تحلیل دسترسی شبکه: courses/advgis/session6.md
      - جلسه ۷ - مسیریابی و مبدا-مقصد شبکه: courses/advgis/session7.md
      - جلسه ۸ - تحلیل کسب‌وکار شبکه: courses/advgis/session8.md
      - جلسه ۹ - آمار فضایی پایه: courses/advgis/session9.md
      - جلسه ۱۰ - رگرسیون فضایی و مدل‌سازی: courses/advgis/session10.md
      - جلسه ۱۱ - تحلیل الگوی آماری-فضایی: courses/advgis/session11.md
      - جلسه ۱۲ - مقدمه WebGIS و معماری: courses/advgis/session12.md
      - جلسه ۱۳ - مبانی طراحی وب: courses/advgis/session13.md
      - جلسه ۱۴ - نقشه تعاملی Leaflet بخش ۱: courses/advgis/session14.md
      - جلسه ۱۵ - نقشه تعاملی Leaflet بخش ۲: courses/advgis/session15.md
      - جلسه ۱۶ - توسعه WebGIS متن‌باز: courses/advgis/session16.md
    - ورود به دنیای برنامه‌نویسی پایتون در GIS: 
      - معرفی دوره: courses/pygis101.md
      - جلسه ۱-مبانی: courses/pygis101/session1.md
      - جلسه ۲-وکتور: courses/pygis101/session2.md
      - جلسه ۳-رستر: courses/pygis101/session3.md
      - جلسه ۴-آمار: courses/pygis101/session4.md
      - جلسه ۵-وب: courses/pygis101/session5.md
  - درباره: about.md
  - تماس: contact.md

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format  
